name: Chromatic

on:
  push:
    branches: [main]
  pull_request:

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        run: npx chromatic --project-token=chpt_e6e21fdc36bdac6
